title = "Nutriton plans"

[nutrition_plans.nutrition_plan1]
description = "nutirition_plan1"

[nutrition_plans.nutrition_plan2]
description = "nutrition_plan2"

[nutrition_plans.nutrition_plan1.meals.meal1]
time = "08:00:00"

[nutrition_plans.nutrition_plan2.meals.meal2]
time = "10:00:00"

[nutrition_plans.nutrition_plan1.meals.meal1.items.item1]
ingredient = "oatmeal"
amount = 3
weight = 200

[nutrition_plans.nutrition_plan1.meals.meal2.items.item1]
ingredient = "4 Eggs"
amount = 3
weight = 200


[nutrition_plans.nutrition_plan2.meals.meal2.items.item1]
ingredient = "eggs"
amount = 3
weight = 500

