title = "Nutrition plans"

[nutrition_plans.nutrition_plan1]
    description = "nutirition_plan1"
    [nutrition_plans.nutrition_plan1.meals.meal1]
        time = "08:00:00"
        [nutrition_plans.nutrition_plan1.meals.meal1.items.item1]
            ingredient = 11206
            amount = 100
        [nutrition_plans.nutrition_plan1.meals.meal1.items.item2]
            ingredient = 11206
            amount = 200
        [nutrition_plans.nutrition_plan1.meals.meal1.items.item3]
            ingredient = 11206
            amount = 300
    [nutrition_plans.nutrition_plan1.meals.meal2]
        time = "12:00:00"
        [nutrition_plans.nutrition_plan1.meals.meal2.items.item1]
            ingredient = 11537
            amount = 100
        [nutrition_plans.nutrition_plan1.meals.meal2.items.item2]
            ingredient = 11537
            amount = 200

    [nutrition_plans.nutrition_plan1.meals.meal3]
        time = "20:00:00"


[nutrition_plans.nutrition_plan2]
    description = "nutrition_plan2"
    [nutrition_plans.nutrition_plan2.meals.meal1]
        time = "10:00:00"
        [nutrition_plans.nutrition_plan2.meals.meal1.items.item1]
            ingredient = 55114
            amount = 100
        [nutrition_plans.nutrition_plan2.meals.meal1.items.item2]
            ingredient = 55114
            amount = 200
        [nutrition_plans.nutrition_plan2.meals.meal1.items.item3]
            ingredient = 55114
            amount = 300


[nutrition_plans.nutrition_plan3]
    description = "nutrition_plan3"














